server:
  port: 10001



#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.linchong.fastdfsmvtool.entity
  mapperLocations: classpath:mapper/*.xml


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://192.168.0.69:3306/dog_or_netword?useUnicode=true&characterEncoding=utf8              # 数据库名称
    username: root
    password: root
    driver-class-name: org.gjt.mm.mysql.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource